{
  "openapi": "3.0.1",
  "info": {
    "title": "NOVAC API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://api.novacpayment.com/"
    }
  ],
  "paths": {
    "/api/v1/initiate": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CheckoutInitRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CheckoutInitRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CheckoutInitRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/paymentlink/initiate": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PaymentLinkInitRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PaymentLinkInitRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PaymentLinkInitRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InitiateFailureResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/checkout/transaction/{transactionRef}": {
      "get": {
        "tags": [
          "Checkout"
        ],
        "parameters": [
          {
            "name": "transactionRef",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/transaction-fee": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/bank-transfer": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionfeeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/card-payment": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CardPaymentRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CardPaymentRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CardPaymentRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/card/validate-otp": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/checkout/{transactionRef}/verify": {
      "get": {
        "tags": [
          "Checkout"
        ],
        "parameters": [
          {
            "name": "transactionRef",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/VerifyStatusSuccessResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/VerifyStatusFailureResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/ussd-getbanks": {
      "get": {
        "tags": [
          "Checkout"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/ussd-payment": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InitiateUSSDPaymentRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/InitiateUSSDPaymentRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/InitiateUSSDPaymentRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/direct-card-charge": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeRequestDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeRequestDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeRequestDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v3/direct-card-charge-internal": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InternalDirectChargeRequestDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/InternalDirectChargeRequestDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/InternalDirectChargeRequestDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/tokenized-card-charge": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TokenizedChargeRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TokenizedChargeRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TokenizedChargeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/transaction/{transactionRef}/verify": {
      "get": {
        "tags": [
          "Collection"
        ],
        "parameters": [
          {
            "name": "transactionRef",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/transaction/verify": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CardVerificationRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CardVerificationRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CardVerificationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/encrypt-data": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CardEncryptionPayload"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CardEncryptionPayload"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CardEncryptionPayload"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/decrypt-data": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeCardEncrypteData"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeCardEncrypteData"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/DirectChargeCardEncrypteData"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/threedschallenge": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/StringStringValuesKeyValuePair"
                    }
                  }
                }
              },
              "encoding": {
                "data": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "get": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/StringStringValuesKeyValuePair"
                    }
                  }
                }
              },
              "encoding": {
                "data": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/direct-card-charge-auth": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ValidateOtpRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/void-transaction": {
      "post": {
        "tags": [
          "Collection"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VoidRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/VoidRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/VoidRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/banks/{countryCode}": {
      "get": {
        "tags": [
          "Payout"
        ],
        "parameters": [
          {
            "name": "countryCode",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessBankListResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FailureBankListresponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/banks/account/verify": {
      "post": {
        "tags": [
          "Payout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AccountNameRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/AccountNameRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/AccountNameRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccountNameSuccessVerify"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccountNameFailureVerify"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/transfers": {
      "post": {
        "tags": [
          "Payout"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransferRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/TransferRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/TransferRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InitiateTransferSuccessResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InitiateTransferFailureResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/transfers/{reference}": {
      "get": {
        "tags": [
          "Payout"
        ],
        "parameters": [
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetTransferStatusSuccesResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetTransferStatusFailureResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/balance/{currency}": {
      "get": {
        "tags": [
          "Payout"
        ],
        "parameters": [
          {
            "name": "currency",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WalletBalanceSuccessResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WalletBalanceFailureResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/refund": {
      "post": {
        "tags": [
          "Refund"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefundRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/RefundRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/RefundRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/partial-refund": {
      "post": {
        "tags": [
          "Refund"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PartialRefundRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/PartialRefundRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/PartialRefundRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/refund/{reference}": {
      "get": {
        "tags": [
          "Refund"
        ],
        "parameters": [
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/refund/{startDate}/{endDate}": {
      "get": {
        "tags": [
          "Refund"
        ],
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RefundResponse"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RefundResponse"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RefundResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/report/{startDate}/{endDate}": {
      "get": {
        "tags": [
          "Report"
        ],
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefundResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/virtual-accounts/bank-list": {
      "get": {
        "tags": [
          "VirtualAccount"
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/virtual-account/{reference}": {
      "get": {
        "tags": [
          "VirtualAccount"
        ],
        "parameters": [
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/virtual-accounts/{accountNumber}": {
      "get": {
        "tags": [
          "VirtualAccount"
        ],
        "parameters": [
          {
            "name": "accountNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/virtual-account": {
      "post": {
        "tags": [
          "VirtualAccount"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VanAccountCreationRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/VanAccountCreationRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/VanAccountCreationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/v1/budpay-incoming-webhook": {
      "post": {
        "tags": [
          "Webhook"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { }
            },
            "text/json": {
              "schema": { }
            },
            "application/*+json": {
              "schema": { }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AccountNameFailureVerify": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": false,
          "message": "Account name not found",
          "data": "string"
        }
      },
      "AccountNameRequest": {
        "required": [
          "account_number",
          "bank_code",
          "currency"
        ],
        "type": "object",
        "properties": {
          "bank_code": {
            "minLength": 1,
            "type": "string"
          },
          "account_number": {
            "minLength": 1,
            "type": "string"
          },
          "currency": {
            "minLength": 1,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "AccountNameSuccessVerify": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": true,
          "message": "Account name retrieved",
          "data": "John"
        }
      },
      "ApiResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "status": true,
          "message": "Transaction Initialized successfully",
          "data": {
            "transactionReference": "string",
            "amount": 0,
            "statusCode": "01",
            "statusMessage": "Transaction initiated successfully",
            "publicKey": "string",
            "paymentRedirectUrl": "string"
          }
        }
      },
      "CardEncryptionPayload": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Data"
          },
          "reference": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CardPaymentRequest": {
        "type": "object",
        "properties": {
          "cardNumber": {
            "type": "string",
            "nullable": true
          },
          "expiryMonth": {
            "type": "string",
            "nullable": true
          },
          "expiryYear": {
            "type": "string",
            "nullable": true
          },
          "cvv": {
            "type": "string",
            "nullable": true
          },
          "cardPin": {
            "type": "string",
            "nullable": true
          },
          "transactionReference": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CardVerificationRequest": {
        "type": "object",
        "properties": {
          "transactionReference": {
            "type": "string",
            "nullable": true
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "transactionType": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CheckoutCustomerData": {
        "required": [
          "email",
          "firstName",
          "lastName"
        ],
        "type": "object",
        "properties": {
          "email": {
            "minLength": 1,
            "type": "string"
          },
          "firstName": {
            "minLength": 1,
            "type": "string"
          },
          "lastName": {
            "minLength": 1,
            "type": "string"
          },
          "phoneNumber": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CheckoutCustomizationData": {
        "type": "object",
        "properties": {
          "logoUrl": {
            "type": "string",
            "nullable": true
          },
          "paymentDescription": {
            "maxLength": 255,
            "minLength": 0,
            "type": "string",
            "nullable": true
          },
          "checkoutModalTitle": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CheckoutInitRequest": {
        "required": [
          "transactionReference"
        ],
        "type": "object",
        "properties": {
          "transactionReference": {
            "maxLength": 50,
            "minLength": 16,
            "type": "string"
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "metaData": {
            "type": "string",
            "nullable": true
          },
          "redirectUrl": {
            "type": "string",
            "nullable": true
          },
          "checkoutCustomerData": {
            "$ref": "#/components/schemas/CheckoutCustomerData"
          },
          "checkoutCustomizationData": {
            "$ref": "#/components/schemas/CheckoutCustomizationData"
          }
        },
        "additionalProperties": false
      },
      "Data": {
        "type": "object",
        "properties": {
          "number": {
            "type": "string",
            "nullable": true
          },
          "expiryMonth": {
            "type": "string",
            "nullable": true
          },
          "expiryYear": {
            "type": "string",
            "nullable": true
          },
          "cvv": {
            "type": "string",
            "nullable": true
          },
          "pin": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "Datum": {
        "type": "object",
        "properties": {
          "bank_name": {
            "type": "string",
            "nullable": true
          },
          "bank_code": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "DirectChargeCardEncrypteData": {
        "type": "object",
        "properties": {
          "encryptedData": {
            "type": "string",
            "nullable": true
          },
          "reference": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "DirectChargeRequestDto": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "number",
            "format": "double"
          },
          "card": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "reference": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "transactionType": {
            "type": "string",
            "nullable": true
          },
          "enforceSecureAuth": {
            "type": "boolean"
          },
          "redirectUrl": {
            "type": "string",
            "nullable": true
          },
          "metaData": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "FailureBankListresponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": false,
          "message": "Not found",
          "currency": "string"
        }
      },
      "GetTransferStatusFailureResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": false,
          "message": "Transaction record not found",
          "data": "string"
        }
      },
      "GetTransferStatusSuccesResponse": {
        "type": "object",
        "additionalProperties": false,
        "example": {
          "success": true,
          "message": "Transfer retrieved",
          "data": {
            "id": "0",
            "sessionId": "string",
            "reference": "string",
            "currency": "NGN",
            "amount": 0,
            "fee": 0,
            "bankCode": "string",
            "bankName": "string",
            "accountNumber": "string",
            "accountName": "string",
            "narration": "string",
            "domain": "test | live",
            "status": "pending | successful | failed",
            "providerResponseMessage": "Transaction successful",
            "updatedAt": "string",
            "createdAt": "string"
          }
        }
      },
      "InitiateFailureResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "status": false,
          "message": "Empty request not allowed.",
          "data": {
            "responseCode": "400",
            "responseDescription": "Invalid request."
          }
        }
      },
      "InitiateTransferFailureResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": false,
          "message": "Transaction Amount must be greater than 0",
          "data": "string"
        }
      },
      "InitiateTransferSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": true,
          "message": "Transfer successfully logged and Processing",
          "data": {
            "id": "0",
            "reference": "string",
            "currency": "NGN",
            "amount": 0,
            "fee": 0,
            "bankCode": "string",
            "bankName": "string",
            "accountNumber": "string",
            "accountName": "string",
            "narration": "string",
            "domain": "test | live",
            "status": "pending",
            "providerResponseMessage": "Transaction successful",
            "updatedAt": "string",
            "createdAt": "string"
          }
        }
      },
      "InitiateUSSDPaymentRequest": {
        "required": [
          "bankCode",
          "transactionReference"
        ],
        "type": "object",
        "properties": {
          "transactionReference": {
            "maxLength": 150,
            "minLength": 0,
            "type": "string"
          },
          "bankCode": {
            "maxLength": 10,
            "minLength": 0,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "InternalDirectChargeRequestDto": {
        "type": "object",
        "properties": {
          "businessId": {
            "type": "integer",
            "format": "int32"
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "transactionType": {
            "type": "string",
            "nullable": true
          },
          "enforceSecureAuth": {
            "type": "boolean"
          },
          "cardData": {
            "$ref": "#/components/schemas/Data"
          },
          "metadata": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "PartialRefundRequest": {
        "required": [
          "amount",
          "reference"
        ],
        "type": "object",
        "properties": {
          "reference": {
            "minLength": 1,
            "type": "string"
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "customer_note": {
            "type": "string",
            "nullable": true
          },
          "merchant_note": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "PaymentLinkInitRequest": {
        "required": [
          "amount",
          "checkoutCustomerData",
          "currency",
          "paymentLinkReference"
        ],
        "type": "object",
        "properties": {
          "paymentLinkReference": {
            "minLength": 1,
            "type": "string"
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "currency": {
            "minLength": 1,
            "type": "string"
          },
          "metaData": {
            "type": "string",
            "nullable": true
          },
          "checkoutCustomerData": {
            "$ref": "#/components/schemas/CheckoutCustomerData"
          },
          "checkoutCustomizationData": {
            "$ref": "#/components/schemas/CheckoutCustomizationData"
          }
        },
        "additionalProperties": false
      },
      "RefundRequest": {
        "required": [
          "reference"
        ],
        "type": "object",
        "properties": {
          "reference": {
            "minLength": 1,
            "type": "string"
          },
          "customer_note": {
            "type": "string",
            "nullable": true
          },
          "merchant_note": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "RefundResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          },
          "refundReference": {
            "type": "string",
            "nullable": true
          },
          "amount": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "domain": {
            "type": "string",
            "nullable": true
          },
          "channel": {
            "type": "string",
            "nullable": true
          },
          "merchantNote": {
            "type": "string",
            "nullable": true
          },
          "customerNote": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "string",
            "nullable": true
          },
          "transactionReference": {
            "type": "string",
            "nullable": true
          },
          "createdAt": {
            "type": "string",
            "nullable": true
          },
          "updatedAt": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "StringStringValuesKeyValuePair": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "nullable": true
          },
          "value": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": false
      },
      "SuccessBankListResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Datum"
            },
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": true,
          "message": "Bank list retrieved",
          "currency": "NGN",
          "data": [
            {
              "bank_name": "First Bank of Nigeria",
              "bank_code": "011"
            },
            {
              "bank_name": "Access Bank",
              "bank_code": "044"
            }
          ]
        }
      },
      "TokenizedChargeRequest": {
        "required": [
          "amount",
          "email",
          "reference",
          "token"
        ],
        "type": "object",
        "properties": {
          "token": {
            "minLength": 1,
            "type": "string"
          },
          "currency": {
            "type": "string",
            "nullable": true
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "email": {
            "minLength": 1,
            "type": "string"
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "reference": {
            "minLength": 1,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "TransactionfeeRequest": {
        "type": "object",
        "properties": {
          "transactionReference": {
            "type": "string",
            "nullable": true
          },
          "paymentType": {
            "type": "string",
            "nullable": true
          },
          "cardBin": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "TransferRequest": {
        "required": [
          "accountNumber",
          "amount",
          "bankCode",
          "currency",
          "narration",
          "reference"
        ],
        "type": "object",
        "properties": {
          "currency": {
            "minLength": 1,
            "type": "string"
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "bankCode": {
            "minLength": 1,
            "type": "string"
          },
          "bankName": {
            "type": "string",
            "nullable": true
          },
          "accountNumber": {
            "minLength": 1,
            "type": "string"
          },
          "accountName": {
            "type": "string",
            "nullable": true
          },
          "narration": {
            "minLength": 1,
            "type": "string"
          },
          "reference": {
            "maxLength": 50,
            "minLength": 10,
            "type": "string"
          },
          "metaData": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ValidateOtpRequest": {
        "type": "object",
        "properties": {
          "reference": {
            "type": "string",
            "nullable": true
          },
          "otp": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VanAccountCreationRequest": {
        "type": "object",
        "properties": {
          "reference": {
            "type": "string",
            "nullable": true
          },
          "amount": {
            "type": "number",
            "format": "double"
          },
          "accountType": {
            "type": "string",
            "nullable": true
          },
          "accountName": {
            "type": "string",
            "nullable": true
          },
          "bankCode": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          },
          "customerEmail": {
            "type": "string",
            "nullable": true
          },
          "expiryInMinutes": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "VerifyStatusFailureResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "status": false,
          "message": "no record found for transaction with reference ....."
        }
      },
      "VerifyStatusSuccessResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "status": true,
          "message": "Transaction details retrieved successfully",
          "data": {
            "status": "pending | successful | failed",
            "id": 0,
            "transactionReference": "string",
            "amount": 0,
            "chargedAmount": 0,
            "currency": "NGN",
            "transactionFee": 0,
            "gatewayResponseCode": "00",
            "gatewayResponseMessage": "string",
            "domain": "string",
            "channel": "string",
            "requestIp": "string",
            "paymentDescriptor": "NOVAC",
            "transactionType": "",
            "redirectUrl": "",
            "card": {
              "first6Digits": "string",
              "last4Digits": "string",
              "issuer": "",
              "country": "string",
              "type": "string"
            },
            "customer": {
              "id": 0,
              "customerCode": "string",
              "email": "string",
              "name": "string"
            },
            "transferDetail": {
              "bankCode": "string",
              "bankName": "string",
              "accountNumber": "string",
              "sessionId": "string",
              "creditAccountName": "string",
              "originatorName": "string",
              "originatorAccountNumber": "string"
            }
          }
        }
      },
      "VoidRequest": {
        "type": "object",
        "properties": {
          "transactionReference": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "WalletBalanceFailureResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": false,
          "message": "Balance information not found",
          "data": "string"
        }
      },
      "WalletBalanceSuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "nullable": true
          }
        },
        "additionalProperties": false,
        "example": {
          "success": true,
          "message": "Balance Fetched Successfully",
          "data": {
            "currency": "NGN",
            "balance": 0
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "Input your Bearer token in this format - Bearer {your token here} to access this API",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "Bearer": [ ]
    }
  ]
}
